# Main page title
title: "Countdown.js Docs"

# Your name
name: "Igor Kowalczyk"

# Site version (used in "/download" dir)
version: "v0.0.2"

# Name of project
project: "Countdown.js"

# Contact E-Mail (Public!)
email: "xxmajonezxx@gmail.com"

# Description
description: "Countdown.js - A simple and easy-to-use countdown"

# Base url (Not link! Only dir, without slash at end)
baseurl: "countdown.js"
url: "https://igorkowalczyk.github.io"

# Github username (no link) - if you don't have - leave blank
github_username:  "igorkowalczyk"
# Repo from github (Not link! Only name, without slash at end)
repo: "countdown.js"
# Branch (eg. master, Not link!)
branch: "master"

# Twitter username (no link) - if you don't have - leave blank
twitter: "@majonezexe"

# First Launch of the site (displays in footer)
first-launch: "2019"

# Timezone
timezone: "Europe/Warsaw"

# Markdown and Default theme
markdown: kramdown
theme: minima

# Support to mobile browsers (It’s unknown what range of browsers support this meta tags) [Better to set the value to "false"!]
mobile: "false"

# Encoding (default: utf-8)
encoding: utf-8

# Exclude files
exclude:
 - Gemfile
 - Gemfile.lock

# Tracking id - if you don't have - leave blank
tracking_id: "UA-174454816-1"

# Verification ID - if you don't have - leave blank
verification: "-wuCsk4qLolXEPSUTGX7YBxywcyNNf5HS2ClzgEWxNY"
