name: Typescript

on:
 push:
  branches: [master]
 pull_request:
  branches: [master]

jobs:
 build:
  name: ✨ Typescript
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v1
   - run: npm i
   - run: npm run build
